log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443

certificatesResolvers:
  letsencrypt:
    acme:
      email: "avi@naamche.com"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    websecure-router:
      rule: 'Host(`demo-transaction.ethan-ai.com`)'
      entryPoints:
        - websecure
      service: chat
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

  services:
    chat:
      loadBalancer:
        servers:
          - url: http://nodejs-app:8000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
